clc,clearvars,close all
%initCobraToolbox

%% Model
%Load model of Bifidobaterium infantis ATCC 15697
load('Bifidobacterium_longum_infantis_ATCC_15697_AGORA.mat')

%Remove reactions not supported by literature
model = removeRxns(model,{'ABTOXy','LCTSabc','FCI','FCLK','FCLPA',...
    'ACGAM2E', 'XYLI1', 'XYLK', 'XYLabc', 'XYLt', 'EX_xyl_D(e)', ...
    'ACGAMtr2','ACGApts', 'ARBabc', 'ARBt2r', 'EX_arab_L(e)',...
    'EX_arabinogal(e)', 'EX_arabttr(e)', 'ARABINOGALASEe',...
    'MANAD_D', 'MNLt6', 'EX_mnl(e)', 'EX_man(e)', ...
    'EX_mantr(e)', 'EX_rmn(e)', 'MAN6PI', 'MANabc', 'ACGALK3',...
    'ACGALt2r', 'AGDC2', 'EX_acgal(e)', 'GALAM6PDA',...
    'EX_T_antigen(e)', 'EX_core2(e)','EX_core3(e)', 'EX_core4(e)',...
    'EX_core5(e)','EX_core6(e)','EX_core7(e)','EX_core8(e)', 'EX_f1a(e)',...
    'EX_gncore1(e)', 'EX_gncore2(e)', 'EX_sT_antigen(e)', ...
    'EX_sTn_antigen(e)'});
model = removeRxns(model,'biomass525', 'metFlag', false);

%Add reaction with correct name 
model = addReaction(model, 'LCTSMFSt','reactionName',...
'lactose permease (import)','reactionFormula',...
'h[e] + lcts[e]  -> h[c] + lcts[c]',...
'subSystem','Transport, extracellular','lowerBound',0,...
    'upperBound',1000,'geneRule','Blon_2331');

%Change gene associations based on literature
model = changeGeneAssociation(model, 'PFK', 'Blon_0877');
model = changeGeneAssociation(model, 'LACZ', '(Blon_2016 or Blon_2334)');
model = changeGeneAssociation(model, 'ACGAMK', 'Blon_0879');
model = changeGeneAssociation(model, 'ACNML', '(Blon_0651 and Blon_2349)');
model = changeGeneAssociation(model, 'AMANK', 'Blon_0644');
model = changeGeneAssociation(model, 'AMANAPEr', 'Blon_0645');

%% Add missing metabolites
model = addMetabolite(model,'lnb[e]','metName','Lacto-N-Biose',...
    'metFormula','C14H25NO11');
model = addMetabolite(model,'lnb[c]','metName','Lacto-N-Biose',...
    'metFormula','C14H25NO11');
model = addMetabolite(model,'gnb[e]','metName','Galacto-N-Biose',...
    'metFormula','C14H25NO11');
model = addMetabolite(model,'gnb[c]','metName','Galacto-N-Biose',...
    'metFormula','C14H25NO11');
model = addMetabolite(model,'mglx[e]','metName','Methylglyoxal',...
    'metFormula','C3H4O2');
model = addMetabolite(model,'mglx[c]','metName','Methylglyoxal',...
    'metFormula','C3H4O2');
model = addMetabolite(model,'lactgsh[c]','metName',...
    '(R)-S-Lactoyglutathione','metFormula','C13H21N3O8S');
model = addMetabolite(model,'lactgsh[e]','metName',...
    '(R)-S-Lactoyglutathione','metFormula','C13H21N3O8S');
model = addMetabolite(model,'gsh[c]','metName','Glutathione',...
    'metFormula','C10H17N3O6S');
model = addMetabolite(model,'gsh[e]','metName','Glutathione',...
    'metFormula','C10H17N3O6S');
model = addMetabolite(model,'acACP[c]','metName',...
    'Acetyl-[acyl-carrier protein]','metFormula','C2H3OSR');
model = addMetabolite(model,'malACP[c]','metName',...
    'Malonyl-[acyl-carrier protein]','metFormula','C3H3O3SR');
model = addMetabolite(model,'3hbutACP[c]','metName',...
    '(R)-3-Hydroxybutanoyl-[acyl-carrier protein]',...
    'metFormula','C4H7O2SR');
model = addMetabolite(model,'but2ACP[c]','metName',...
    'But-2-enoyl-[acyl-carrier protein]','metFormula','C4H5OSR');
model = addMetabolite(model,'butACP[c]','metName',...
    'Butanoyl-[acyl-carrier protein]','metFormula','C4H7OSR');
model = addMetabolite(model,'thexACP[c]','metName',...
    'trans-Hex-2-enoyl-[acyl-carrier protein]','metFormula','C6H9OSR');
model = addMetabolite(model,'hexACP[c]','metName',...
    'Hexanoyl-[acyl-carrier protein]','metFormula','C6H11OSR');
model = addMetabolite(model,'toctACP[c]','metName',...
    'trans-Oct-2-enoyl-[acyl-carrier protein]','metFormula','C8H13OSR');
model = addMetabolite(model,'octACP[c]','metName',...
    'Octanoyl-[acyl-carrier protein]','metFormula','C8H15OSR');
model = addMetabolite(model,'tdecACP[c]','metName',...
    'trans-Dec-2-enoyl-[acyl-carrier protein]','metFormula','C10H17OSR');
model = addMetabolite(model,'decACP[c]','metName',...
    'Decanoyl-[acyl-carrier protein]','metFormula','C10H19OSR');
model = addMetabolite(model,'tddecACP[c]','metName',...
    'trans-Dodec-2-enoyl-[acyl-carrier protein]','metFormula','C12H21OSR');
model = addMetabolite(model,'tmrsACP[c]','metName',...
    'trans-Tetradec-2-enoyl-[acyl-carrier protein]',...
    'metFormula','C14H25OSR');
model = addMetabolite(model,'tpalmACP[c]','metName',...
    'trans-Hexadec-2-enoyl-[acyl-carrier protein]',...
    'metFormula','C16H29OSR');
model = addMetabolite(model,'toctdACP[c]','metName',...
    'trans-Octadec-2-enoyl-[acyl-carrier protein]',...
    'metFormula','C18H33OSR');
model = addMetabolite(model,'LTA[c]','metName','Lipoteichoic Acid');

%% Add missing reactions
model = addReaction(model,'TRAN_mglx','metaboliteList',{'mglx[c]',...
    'mglx[e]'},'stoichCoeffList',[-1,1],'lowerBound',0,'upperBound',1000,...
    'subSystem','Transport, extracellular');
model = addReaction(model,'EX_mglx(e)','metaboliteList',{'mglx[e]'},...
    'stoichCoeffList',-1,'lowerBound',0,'upperBound',1000,...
    'subSystem','Exchange/demand reaction');
model = addReaction(model,'TRAN_lactgsh','metaboliteList',{'lactgsh[c]',...
    'lactgsh[e]'},'stoichCoeffList',[-1,1],'lowerBound',0,...
    'upperBound',1000,'subSystem','Transport, extracellular');
model = addReaction(model,'EX_lactgsh(e)','metaboliteList',...
    {'lactgsh[e]'},'stoichCoeffList',-1,'lowerBound',0,'upperBound',1000,...
    'subSystem','Exchange/demand reaction');
model = addReaction(model,'TRAN_gsh','metaboliteList',{'gsh[c]',...
    'gsh[e]'},'stoichCoeffList',[-1,1],'lowerBound',0,'upperBound',1000,...
    'subSystem','Transport, extracellular');
model = addReaction(model,'EX_gsh(e)','metaboliteList',{'gsh[e]'},...
    'stoichCoeffList',-1,'lowerBound',0,'upperBound',1000,...
    'subSystem','Exchange/demand reaction');
model = addReaction(model,'lald_mglx','metaboliteList',{'lald_L[c]',...
    'nadp[c]','mglx[c]','nadph[c]','h[c]'},'stoichCoeffList',...
    [-1,-1,1,1,1],'lowerBound',0,'upperBound',1000,'geneRule','Blon_0820',...
    'subSystem','Glyoxylate and dicarboxylate metabolism');
model = addReaction(model,'mglx_lactgsh','metaboliteList',{'gsh(c)',...
    'mglx(c)','lactgsh(c)'},'stoichCoeffList',[-1,-1,1],'lowerBound',0,...
    'upperBound',1000,'geneRule','Blon_0290',...
    'subSystem','Glyoxylate and dicarboxylate metabolism');
model = addReaction(model,'acCOAACP','metaboliteList',{'accoa[c]',...
    'ACP[c]','coa[c]','acACP[c]'},'stoichCoeffList',[-1,-1,1,1],...
    'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'malCOAACP','metaboliteList',{'malcoa[c]',...
    'ACP[c]','coa[c]','malACP[c]'},'stoichCoeffList',[-1,-1,1,1],...
    'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'acmalACP','metaboliteList',{'acACP[c]',...
    'malACP[c]','actACP[c]','co2[c]','ACP[c]'},'stoichCoeffList',...
    [-1,-1,1,1,1],'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'3hbutACP','metaboliteList',{'actACP[c]',...
    'nadph[c]','h[c]','3hbutACP[c]','nadp[c]'},'stoichCoeffList',...
    [-1,-1,-1,1,1],'lowerBound',0,'upperBound',1000,'geneRule',...
    'Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'but2ACP','metaboliteList',{'3hbutACP[c]',...
    'h2o[c]','but2ACP[c]'},'stoichCoeffList',[-1,1,1],'lowerBound',...
    0,'upperBound',1000,'geneRule','Blon_2284','subSystem',...
    'Fatty acid synthesis');
model = addReaction(model,'butACP','metaboliteList',{'but2ACP[c]',...
    'nadh[c]','h[c]','butACP[c]','nad[c]'},'stoichCoeffList',...
    [-1,-1,-1,1,1],'lowerBound',0,'upperBound',1000,'geneRule',...
    'Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'butmalACP','metaboliteList',{'butACP[c]',...
    'malACP[c]','3ohexACP[c]','co2[c]','ACP[c]'},'stoichCoeffList',...
    [-1,-1,1,1,1],'lowerBound',0,'upperBound',1000,'geneRule',...
    'Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'3ohexto3hhexACP','metaboliteList',...
    {'3ohexACP[c]','nadph[c]','h[c]','3hhexACP[c]','nadp[c]'},...
    'stoichCoeffList',[-1,-1,-1,1,1],'lowerBound',0,'upperBound',1000,...
    'geneRule','Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'3hhextothexACP','metaboliteList',...
    {'3hhexACP[c]','thexACP[c]','h2o[c]'},'stoichCoeffList',[-1,1,1],...
    'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'thextohexACP','metaboliteList',...
    {'thexACP[c]','nadh[c]','h[c]','hexACP[c]','nad[c]'},...
    'stoichCoeffList',[-1,-1,-1,1,1],'lowerBound',0,'upperBound',...
    1000,'geneRule','Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'hexmalACP','metaboliteList',{'hexACP[c]',...
    'malACP[c]','3ooctACP[c]','co2[c]','ACP[c]'},'stoichCoeffList',...
    [-1,-1,1,1,1],'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'3ooctto3hoctACP','metaboliteList',...
    {'3ooctACP[c]','nadph[c]','h[c]','3hoctACP[c]','nadp[c]'},...
    'stoichCoeffList',[-1,-1,-1,1,1],'lowerBound',0,'upperBound',...
    1000,'geneRule','Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'3hocttotoctACP','metaboliteList',...
    {'3hoctACP[c]','toctACP[c]','h2o[c]'},'stoichCoeffList',[-1,1,1],...
    'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'tocttooctACP','metaboliteList',...
    {'toctACP[c]','nadh[c]','h[c]','octACP[c]','nad[c]'},...
    'stoichCoeffList',[-1,-1,-1,1,1],'lowerBound',0,'upperBound',...
    1000,'geneRule','Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'octmalACP','metaboliteList',{'octACP[c]',...
    'malACP[c]','3odecACP[c]','co2[c]','ACP[c]'},'stoichCoeffList',...
    [-1,-1,1,1,1],'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'3odecto3hdecACP','metaboliteList',...
    {'3odecACP[c]','nadph[c]','h[c]','3hdecACP[c]','nadp[c]'},...
    'stoichCoeffList',[-1,-1,-1,1,1],'lowerBound',0,'upperBound',1000,...
    'geneRule','Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'3hdectotdecACP','metaboliteList',...
    {'3hdecACP[c]','tdecACP[c]','h2o[c]'},'stoichCoeffList',[-1,1,1],...
    'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'tdectodecACP','metaboliteList',...
    {'tdecACP[c]','nadh[c]','h[c]','decACP[c]','nad[c]'},...
    'stoichCoeffList',[-1,-1,-1,1,1],'lowerBound',0,'upperBound',...
    1000,'geneRule','Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'decmalACP','metaboliteList',{'decACP[c]',...
    'malACP[c]','3oddecACP[c]','co2[c]','ACP[c]'},'stoichCoeffList',...
    [-1,-1,1,1,1],'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'3oddecto3hddecACP','metaboliteList',...
    {'3oddecACP[c]','nadph[c]','h[c]','3hddecACP[c]','nadp[c]'},...
    'stoichCoeffList',[-1,-1,-1,1,1],'lowerBound',0,'upperBound',1000,...
    'geneRule','Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'3hddectotddecACP','metaboliteList',...
    {'3hddecACP[c]','tddecACP[c]','h2o[c]'},'stoichCoeffList',[-1,1,1],...
    'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'tddectoddcaACP','metaboliteList',...
    {'tddecACP[c]','nadh[c]','h[c]','ddcaACP[c]','nad[c]'},...
    'stoichCoeffList',[-1,-1,-1,1,1],'lowerBound',0,'upperBound',...
    1000,'geneRule','Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'ddcamalACP','metaboliteList',{'ddcaACP[c]',...
    'malACP[c]','3omrsACP[c]','co2[c]','ACP[c]'},'stoichCoeffList',...
    [-1,-1,1,1,1],'lowerBound',0,'upperBound',1000,'geneRule',...
    'Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'3omrsto3hmrsACP','metaboliteList',...
    {'3omrsACP[c]','nadph[c]','h[c]','3hmrsACP[c]','nadp[c]'},...
    'stoichCoeffList',[-1,-1,-1,1,1],'lowerBound',0,'upperBound',1000,...
    'geneRule','Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'3hmrstotmrsACP','metaboliteList',...
    {'3hmrsACP[c]','tmrsACP[c]','h2o[c]'},'stoichCoeffList',[-1,1,1],...
    'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'tmrstomyrsACP','metaboliteList',...
    {'tmrsACP[c]','nadh[c]','h[c]','myrsACP[c]','nad[c]'},...
    'stoichCoeffList',[-1,-1,-1,1,1],'lowerBound',0,'upperBound',...
    1000,'geneRule','Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'myrsmalACP','metaboliteList',{'myrsACP[c]',...
    'malACP[c]','3opalmACP[c]','co2[c]','ACP[c]'},'stoichCoeffList',...
    [-1,-1,1,1,1],'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'3opalmto3hpalmACP','metaboliteList',...
    {'3opalmACP[c]','nadph[c]','h[c]','3hpalmACP[c]','nadp[c]'},...
    'stoichCoeffList',[-1,-1,-1,1,1],'lowerBound',0,'upperBound',1000,...
    'geneRule','Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'3hpalmtotpalmACP','metaboliteList',...
    {'3hpalmACP[c]','tpalmACP[c]','h2o[c]'},'stoichCoeffList',[-1,1,1],...
    'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'tpalmtopalmACP','metaboliteList',...
    {'tpalmACP[c]','nadh[c]','h[c]','palmACP[c]','nad[c]'},...
    'stoichCoeffList',[-1,-1,-1,1,1],'lowerBound',0,'upperBound',...
    1000,'geneRule','Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'palmmalACP','metaboliteList',{'palmACP[c]',...
    'malACP[c]','3ooctdACP[c]','co2[c]','ACP[c]'},'stoichCoeffList',...
    [-1,-1,1,1,1],'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'3ooctdto3hoctaACP','metaboliteList',...
    {'3ooctdACP[c]','nadph[c]','h[c]','3hoctaACP[c]','nadp[c]'},...
    'stoichCoeffList',[-1,-1,-1,1,1],'lowerBound',0,'upperBound',...
    1000,'geneRule','Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'3hoctatotoctdACP','metaboliteList',...
    {'3hoctaACP[c]','toctdACP[c]','h2o[c]'},'stoichCoeffList',...
    [-1,1,1],'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'toctdtoocdaACP','metaboliteList',...
    {'toctdACP[c]','nadh[c]','h[c]','ocdcaACP[c]','nad[c]'},...
    'stoichCoeffList',[-1,-1,-1,1,1],'lowerBound',0,'upperBound',...
    1000,'geneRule','Blon_2284','subSystem','Fatty acid synthesis');
model = addReaction(model,'palmACPtopmtcoa','metaboliteList',...
    {'palmACP[c]','coa[c]','pmtcoa[c]','ACP[c]'},'stoichCoeffList',...
    [-1,-1,1,1],'lowerBound',0,'upperBound',1000,'geneRule','Blon_2284',...
    'subSystem','Fatty acid synthesis');
model = addReaction(model,'12acpg3p','metaboliteList',{'ddcaACP[c]',...
    'glyc3p[c]','1ddecg3p[c]','ACP[c]'},'stoichCoeffList',[-1,-1,1,1],...
    'lowerBound',0,'upperBound',1000,'geneRule','Blon_0956',...
    'subSystem','Glycerophospholipid metabolism');
model = addReaction(model,'14acpg3p','metaboliteList',{'myrsACP[c]',...
    'glyc3p[c]','1tdecg3p[c]','ACP[c]'},'stoichCoeffList',[-1,-1,1,1],...
    'lowerBound',0,'upperBound',1000,'geneRule','Blon_0956',...
    'subSystem','Glycerophospholipid metabolism');
model = addReaction(model,'16acpg3p','metaboliteList',{'palmACP[c]',...
    'glyc3p[c]','1hdecg3p[c]','ACP[c]'},'stoichCoeffList',[-1,-1,1,1],...
    'lowerBound',0,'upperBound',1000,'geneRule','Blon_0956',...
    'subSystem','Glycerophospholipid metabolism');
model = addReaction(model,'18acpg3p','metaboliteList',{'octdACP[c]',...
    'glyc3p[c]','1odecg3p[c]','ACP[c]'},'stoichCoeffList',[-1,-1,1,1],...
    'lowerBound',0,'upperBound',1000,'geneRule','Blon_0956',...
    'subSystem','Glycerophospholipid metabolism');
model = addReaction(model, 'myrstca1','metaboliteList',{'ctp[c]',...
    'g3p[c]','udpg[c]','h2o[c]','pa140', 'cmp[c]','h[c]', 'myrstca1[c]',...
    'pi[c]','udp[c]','ppi[c]'},'stoichCoeffList',...
    [-24,-24,-2,-1,-1,24,25,1,1,2,24],'lowerBound',0,'upperBound',1000,...
    'subSystem','Cell wall biosynthesis');
model = addReaction(model, 'palmtca1','metaboliteList',{'ctp[c]',...
    'g3p[c]','udpg[c]','h2o[c]','pa160', 'cmp[c]','h[c]', ...
    'palmtca1[c]','pi[c]','udp[c]','ppi[c]'},'stoichCoeffList',...
    [-24,-24,-2,-1,-1,24,25,1,1,2,24],'lowerBound',0,'upperBound',1000,...
    'subSystem','Cell wall biosynthesis');
model = addReaction(model, 'sttca1','metaboliteList',{'ctp[c]',...
    'g3p[c]','udpg[c]','h2o[c]','pa180', 'cmp[c]','h[c]', 'sttca1[c]',...
    'pi[c]','udp[c]','ppi[c]'},'stoichCoeffList',...
    [-24,-24,-2,-1,-1,24,25,1,1,2,24],'lowerBound',0,'upperBound',1000,...
    'subSystem','Cell wall biosynthesis');
model = addReaction(model,'LTA','metaboliteList',{'myrstca1[c]',...
    'myrstcaacgam[c]','palmtca1[c]','palmtcaacgam[c]','sttca1[c]',...
    'sttcaacgam[c]','LTA[c]'},'stoichCoeffList',...
    [-0.001122,-0.0004655,-0.004866,-0.002032,-0.001761,-0.0007401,1],...
    'lowerBound',0,'upperBound',1000,'subSystem','Cell wall biosynthesis');
model = addReaction(model, 'UreaABCPP', 'metaboliteList', {'atp[c]',...
   'h2o[c]','urea[e]','adp[c]','h[c]','pi[c]','urea[c]'},...
   'stoichCoeffList', [-1,-1,-1,1,1,1,1], 'lowerBound', 0, 'upperBound',...
   1000,'geneRule','Blon_0104 and Blon_0105 and Blon_0106 and Blon_0107 and Blon_0108 and Blon_109',...
   'subSystem','Transport, extracellular','reactionName',...
   'Urea transport via ABC system (periplasm)');
%This should correspond to periplasmic urea, but this model doesn't contain
%periplasmic compartment
%% Add sink reactions 
%Because the reactions are present but optimizing the biomass doesn't favor
%the flux through them.
model = addSinkReactions(model,{'LTA[c]'}, 0, 1000);
model = addSinkReactions(model,{'pgp120[c]'}, 0, 1000);
model = addSinkReactions(model,{'pgp140[c]'}, 0, 1000);
model = addSinkReactions(model,{'pgp160[c]'}, 0, 1000);
model = addSinkReactions(model,{'pgp180[c]'}, 0, 1000);

%% LNB
%Add exchange reaction of Lacto N biose[e]
model = addReaction(model, 'EX_Lacto_N_Biose(e)', 'metaboliteList',...
    {'lnb[e]'},'stoichCoeffList', -1, 'lowerBound', -1000, ...
    'upperBound' , 0,'subSystem','Exchange/demand reaction',...
    'reactionName','Exchange of Lacto-N-biose');
%Convert lnb[e] into lnb[c] ABC transporter
model = addReaction(model, 'lnbABCt', 'metaboliteList', {'lnb[e]', ...
    'atp[c]','h2o[c]','lnb[c]', 'adp[c]', 'h[c]', 'pi[c]'},...
    'stoichCoeffList', [-1,-1,-1,1,1,1,1], 'lowerBound', 0, 'upperBound',...
    0,'geneRule','(Blon_2177 or Blon_0883) and Blon_2475',...
    'subSystem','Transport, extracellular','reactionName',...
    'ABC transport of Lacto-N-biose');
%Convert lnb[c] into gal1p[c] and acgam[c] 
model = addReaction(model, 'LNBP', 'metaboliteList', {'lnb[c]', ...
    'pi[c]','acgam[c]','gal1p[c]'},'stoichCoeffList', ...
    [-1, -1, 1, 1], 'lowerBound', 0, 'upperBound' , 1000, 'geneRule',...
    'Blon_2174','subSystem','HMO metabolism','reactionName',...
    'lacto-N-biose phosphorylase');
%% GNB
%Add exchange reaction of Galacto N biose[e]
model = addReaction(model, 'EX_Galacto_N_biose(e)', 'metaboliteList',...
    {'gnb[e]'},'stoichCoeffList', -1, 'lowerBound', -1000, ...
    'upperBound' , 0,'subSystem','Exchange/demand reaction',...
    'reactionName','Exchange of Galacto-N-biose');
%Convert gnb[e] into gnb[c] ABC transporter
model = addReaction(model, 'gnbABCt', 'metaboliteList', {'gnb[e]', ...
    'atp[c]','h2o[c]','gnb[c]', 'adp[c]', 'h[c]', 'pi[c]'},...
    'stoichCoeffList', [-1,-1,-1,1,1,1,1], 'lowerBound', 0, 'upperBound',...
    1000,'geneRule','(Blon_2177 or Blon_2350 or Blon_0883) and Blon_2475',...
    'subSystem','Transport, extracellular','reactionName',...
    'ABC transport of Galacto-N-biose');
%Convert gnb[c] into acgal[c] 
model = addReaction(model, 'GNBP', 'metaboliteList', {'lnb[c]', ...
    'pi[c]','acgal[c]','gal1p[c]'},'stoichCoeffList', ...
    [-1, -1, 1, 1], 'lowerBound', 0, 'upperBound' , 1000, 'geneRule',...
    'Blon_2174','subSystem','HMO metabolism','reactionName',...
    'galacto-N-biose phosphorylase');

%% LNT
%Add compound lnt[e]
model = addMetabolite(model, 'lnt[e]', 'metName', 'Lacto-N-tetraose', ...
    'metFormula', 'C26H45NO21');
%Add exchange reaction of Lacto N tetraose[e]
model = addReaction(model, 'EX_Lacto_N_Tetraose(e)', 'metaboliteList',...
    {'lnt[e]'},'stoichCoeffList', -1, 'lowerBound', -1000, ...
    'upperBound' , 0,'subSystem','Exchange/demand reaction',...
    'reactionName','Exchange of Lacto-N-tetraose');
%Add compound lnt[c]
model = addMetabolite(model, 'lnt[c]', 'metName', 'Lacto-N-tetraose', ...
    'metFormula', 'C26H45NO21');
%Add compound GlcNAc-Gal-Glc[c]
model = addMetabolite(model, 'GlcNAc-gal-glc[c]', 'metName', ...
    'N-Acetylglucosamine-gal-glc','metFormula','C20H35NO16');
%Convert lnt[e] into lnt[c] ABC transporter
model = addReaction(model, 'lntABCt', 'metaboliteList', {'lnt[e]', ...
    'atp[c]','h2o[c]','lnt[c]', 'adp[c]', 'h[c]', 'pi[c]'},...
    'stoichCoeffList', [-1,-1,-1,1,1,1,1], 'lowerBound', 0, 'upperBound',...
    1000,'geneRule','(Blon_2177 or Blon_2344 or Blon_2347) and Blon_2475',...
    'subSystem','Transport, extracellular','reactionName',...
    'ABC transport of Lacto-N-tetraose');
%Convert lnt[c] into GlcNAc-gal-glc[c] by 1->3 galactosidase 
model = addReaction(model, 'lntgly', 'metaboliteList', {'lnt[c]', ...
    'h2o[c]','GlcNAc-gal-glc[c]','gal[c]'},'stoichCoeffList', ...
    [-1, -1, 1, 1], 'lowerBound', 0, 'upperBound' , 1000, 'geneRule',...
    'Blon_2016','subSystem','HMO metabolism','reactionName',...
    'Beta 1-3 galactosidase');
%Convert GlcNAc-gal-glc[c] into acgam[c] beta hexosaminidase
model = addReaction(model, 'GlcNAc-gal-glcgly2', 'metaboliteList', ...
    {'GlcNAc-gal-glc[c]', 'h2o[c]','acgam[c]','lcts[c]'},...
    'stoichCoeffList', [-1, -1, 1, 1], 'lowerBound', 0, 'upperBound' ,...
    1000, 'geneRule','Blon_0459 or Blon_0732 or Blon_2355',...
    'subSystem','HMO metabolism','reactionName','Beta hexosaminidase');

%% LNNT
%Add compound lnnt[e]
model = addMetabolite(model, 'lnnt[e]', 'metName','Lacto-N-neotetraose',...
    'metFormula', 'C26H45NO21');
%Add compound lnnt[c]
model = addMetabolite(model, 'lnnt[c]', 'metName','Lacto-N-neotetraose',...
    'metFormula', 'C26H45NO21');
%Add exchange reaction of lacto N neotetraose
model = addReaction(model, 'EX_Lacto_N_Neotetraose(e)','metaboliteList',...
    {'lnnt[e]'},'stoichCoeffList', -1, 'lowerBound', -1000, ...
    'upperBound' , 0,'subSystem','Exchange/demand reaction',...
    'reactionName','Exchange of Lacto-N-neotetraose');
%Convert lnnt[e] into lnnt[c] ABC transporter
model = addReaction(model, 'lnntABCt', 'metaboliteList', {'lnnt[e]', ...
    'atp[c]','h2o[c]','lnnt[c]', 'adp[c]', 'h[c]', 'pi[c]'},...
    'stoichCoeffList', [-1,-1,-1,1,1,1,1], 'lowerBound', 0,...
    'upperBound' , 1000,'geneRule',...
    '(Blon_2177 or Blon_2344 or Blon_2347) and Blon_2475',...
    'subSystem','Transport, extracellular','reactionName',...
    'ABC transport of Lacto-N-neotetraose');
%Convert lnnt[c] into GLcNAc-gal-glc[c] by galactosidase 1->4
model = addReaction(model, 'lnntgly', 'metaboliteList', {'lnnt[c]', ...
    'h2o[c]','GlcNAc-gal-glc[c]','gal[c]'},'stoichCoeffList', ...
    [-1, -1, 1, 1], 'lowerBound', 0, 'upperBound' , 1000, 'geneRule',...
    'Blon_2334','subSystem','HMO metabolism', 'reactionName', ...
    'Beta 1-4 galactosidase');

%% 2FL
%Add compound 2fl[e]
model = addMetabolite(model, '2fl[e]', 'metName', '2-fucosyllactose', ...
    'metFormula', 'C18H32O15');
%Add compound 2fl[c]
model = addMetabolite(model, '2fl[c]', 'metName', '2-fucosyllactose', ...
    'metFormula', 'C18H32O15');
%Add exchange reaction of 2fl[e]
model = addReaction(model, 'EX_2fucosyllactose(e)', 'metaboliteList', ...
    {'2fl[e]'},'stoichCoeffList', -1, 'lowerBound', -1000, ...
    'upperBound' , 0,'subSystem','Exchange/demand reaction',...
    'reactionName','Exchange of 2-Fucosyllactose');
%Convert 2fl[e] into 2fl[c] ABC transporter
model = addReaction(model, '2flABCt', 'metaboliteList', {'2fl[e]',...
     'atp[c]','h2o[c]','2fl[c]', 'adp[c]', 'h[c]', 'pi[c]'},...
    'stoichCoeffList', [-1,-1,-1,1,1,1,1], 'lowerBound', 0,...
    'upperBound' , 1000,'geneRule','(Blon_0343 or Blon_2202) and Blon_2475',...
    'subSystem','Transport, extracellular','reactionName',...
    'ABC transport of 2-Fucosyllactose');
%Convert 2fl[c] into fuc_L[c] by alpha fucosidase
model = addReaction(model, '2flgly', 'metaboliteList', {'2fl[c]',...
    'h2o[c]','lcts[c]','fuc_L[c]'},'stoichCoeffList', [-1, -1, 1, 1],...
    'lowerBound', 0, 'upperBound' , 1000, 'geneRule','Blon_2335 or Blon_0426 or Blon_0248',...
    'subSystem','HMO metabolism','reactionName','Alpha 1-2 fucosidase');
%Add compound fucB_L[c]
model = addMetabolite(model, 'fucB_L[c]', 'metName', 'L-Fuco-Beta-pyranose', ...
    'metFormula', 'C6H12O5');
%Add fumB reaction: L-fucose mutarotase
model = addReaction(model, 'fumB', 'metaboliteList', {'fuc_L[c]',...
    'fucB_L[c]'},'stoichCoeffList', [-1, 1], 'lowerBound', 0,...
    'upperBound' , 1000,'geneRule','Blon_2305 or Blon_2337',...
    'subSystem','Fructose and mannose metabolism', 'reactionName',...
    'L-Fucose mutarotase');
%Add compound fucB_L[c]
model = addMetabolite(model, 'fuc14lac_L[c]', 'metName', 'L-Fucono-1,4-lactone', ...
    'metFormula', 'C6H10O5');
%Add fumC reaction: L-fucose dehydrogenase
model = addReaction(model, 'fumC', 'metaboliteList', {'fucB_L[c]',...
    'nad[c]','fuc14lac_L[c]','nadh[c]','h[c]'},'stoichCoeffList',...
    [-1, -1, 1, 1, 1], 'lowerBound', 0,'upperBound' , 1000,'geneRule',...
    'Blon_2308 or Blon_2339','subSystem','Fructose and mannose metabolism',...
    'reactionName','L-Fucose dehydrogenase');
%Add compound fuco_L[c]
model = addMetabolite(model, 'fuco_L[c]', 'metName', 'L-Fuconate', ...
    'metFormula', 'C6H12O6');
%Add fumD reaction: L-fuconolactone hydrolase
model = addReaction(model, 'fumD', 'metaboliteList', {'fuc14lac_L[c]',...
    'h2o[c]','fuco_L[c]'},'stoichCoeffList',[-1, -1, 1], 'lowerBound', 0,...
    'upperBound' , 1000,'geneRule','Blon_2306','subSystem',...
    'Fructose and mannose metabolism', 'reactionName',...
    'L-Fuconolactone hydrolase');
%Add compound 2k3dfuc_L[c]
model = addMetabolite(model, '2k3dfuc_L[c]', 'metName', ...
    '2-Keto-3-Deoxy-L-Fuconate','metFormula', 'C6H10O5');
%Add fumE reaction: L-fuconate dehydratase
model = addReaction(model, 'fumE', 'metaboliteList', {'fuco_L[c]',...
    'h2o[c]','2k3dfuc_L[c]'},'stoichCoeffList',[-1, 1, 1], 'lowerBound', 0,...
    'upperBound' , 1000,'geneRule','Blon_2309 or Blon_2340','subSystem',...
    'Fructose and mannose metabolism', 'reactionName',...
    'L-fuconate dehydratase');
%Add fumF reaction 2-keto-3-deoxy-L-fuconate aldolase
model = addReaction(model, 'fumF', 'metaboliteList', {'2k3dfuc_L[c]',...
    'pyr[c]','lald_L[c]'},'stoichCoeffList',[-1, 1, 1], 'lowerBound', 0,...
    'upperBound' , 1000,'geneRule','Blon_2338','subSystem',...
    'Fructose and mannose metabolism', 'reactionName',...
    '2-Keto-3-Deoxy-L-Fuconate aldolase');

%% 3FL
%Add compound 3fl[e]
model = addMetabolite(model, '3fl[e]', 'metName', '3-fucosyllactose', ...
    'metFormula', 'C18H32O15');
%Add compound 3fl[c]
model = addMetabolite(model, '3fl[c]', 'metName', '3-fucosyllactose', ...
    'metFormula', 'C18H32O15');
%Add exchange reaction 3fl
model = addReaction(model, 'EX_3fucosyllactose(e)', 'metaboliteList', ...
    {'3fl[e]'},'stoichCoeffList', -1, 'lowerBound', -1000, ...
    'upperBound' , 0,'subSystem','Exchange/demand reaction',...
    'reactionName','Exchange of 3-Fucosyllactose');
%Convert 3fl[e] into 3fl[c] ABC transporter
model = addReaction(model, '3flABCt', 'metaboliteList', {'3fl[e]', ...
     'atp[c]','h2o[c]','3fl[c]', 'adp[c]', 'h[c]', 'pi[c]'},...
    'stoichCoeffList', [-1,-1,-1,1,1,1,1], 'lowerBound', 0, ...
    'upperBound' , 1000,'geneRule','(Blon_0343 or Blon_2202) and Blon_2475',...
    'subSystem','Transport, extracellular','reactionName',...
    'ABC transport of 3-Fucosyllactose');
%Convert 3fl[c] into fuc_L[c]
model = addReaction(model, '3flgly1', 'metaboliteList', {'3fl[c]', ...
    'h2o[c]','lcts[c]','fuc_L[c]'},'stoichCoeffList', [-1, -1, 1, 1], ...
    'lowerBound', 0, 'upperBound' , 1000,'geneRule',...
    'Blon_2335 or Blon_2336 or Blon_0426 or Blon_0248','subSystem',...
    'HMO metabolism','reactionName','Alpha 1-3 fucosidase');

%% 6SL
%Add compound 6sl[e]
model = addMetabolite(model, '6sl[e]', 'metName', '6-sialyllactose', ...
    'metFormula', 'C23H39NO19');
%Add compound 6sl[c]
model = addMetabolite(model, '6sl[c]', 'metName', '6-sialyllactose',...
    'metFormula', 'C23H39NO19');
%Add exchange reaction 6sl[e]
model = addReaction(model, 'EX_6sialyllactose(e)', 'metaboliteList', ...
    {'6sl[e]'},'stoichCoeffList', -1, 'lowerBound', -1000, ...
    'upperBound' , 0,'subSystem','Exchange/demand reaction',...
    'reactionName','Exchange of 6-Sialyllactose');
%Convert 6sl[e] into 6sl[c] by MFS permease
model = addReaction(model, '6slMFSt', 'metaboliteList', {'6sl[e]', ...
    'atp[c]','h2o[c]', 'adp[c]', 'h[c]', 'pi[c]', '6sl[c]'},...
    'stoichCoeffList', [-1,-1,-1,1,1,1,1], 'lowerBound', 0, ...
    'upperBound' , 1000, 'geneRule','Blon_2475',...
    'subSystem','Transport, extracellular',...
    'reactionName','MFS permease of 6-Sialyllactose');
%Convert 6sl[c] into acnam[c] and lcts[c] by alpha sialidase
model = addReaction(model, '6slgly', 'metaboliteList', {'6sl[c]', ...
    'h2o[c]','acnam[c]','lcts[c]'},'stoichCoeffList', ...
    [-1, -1, 1, 1], 'lowerBound', 0, 'upperBound' , 1000,'geneRule',...
    'Blon_2348','subSystem','HMO metabolism','reactionName',...
    'Alpha 2-6 sialidase');

%% Changing exchange reactions bounds
% Make a list of all the exchange reactions that might be used a carbon
% sources or are not present in MRS broth
reactionC= {'EX_lcts(e)',... % lactose
            'EX_Lacto_N_Tetraose(e)',... % lnt
            'EX_Lacto_N_Neotetraose(e)', ... % lnnt
            'EX_2fucosyllactose(e)', ... % 2fl
            'EX_3fucosyllactose(e)', ... % 3fl
            'EX_6sialyllactose(e)', ... % 6sl
            'EX_malt(e)', ... % maltose
            'EX_malthx(e)', ... % maltohexose
            'EX_malttr(e)', ... % maltotriose
            'EX_melib(e)', ... % melibiose
            'EX_oxa(e)', ... % oxalate
            'EX_raffin(e)', ... % raffinose
            'EX_rib_D(e)', ... % ribose
            'EX_stys(e)', ... % stachyose
            'EX_dextrin(e)', ... % dextrin
            'EX_etoh(e)', ... % ethanol
            'EX_for(e)', ... % formate
            'EX_fru(e)', ... % fructose
            'EX_fuc_L(e)', ... % fucose
            'EX_gal(e)', ... % galactose
            'EX_gcald(e)', ... % glycoaldehide
            'EX_glc_D(e)', ... % glucose
            'EX_glcur(e)', ... % glucuronate
            'EX_glyc(e)', ... % glycerol
            'EX_glyc3p(e)', ... % glycerol 3 phosphate
            'EX_inulin(e)', ... % inulin
            'EX_kesto(e)', ... % kestose
            'EX_kestopt(e)', ... % kestopentaose
            'EX_kestottr(e)', ... % kestotetraose
            'EX_lac_L(e)', ... % lactate
            'EX_12ppd_S(e)', ... % propane 1,2 diol
            'EX_ac(e)', ... % acetate
            'EX_acald(e)', ... % acetaldehyde
            'EX_acgam(e)', ... % n-acetyl-d-glucosamine
            'EX_acnam(e)', ... % n-acetilneuraminate
            'EX_arbt(e)', ... % arbutin
            'EX_chtbs(e)', ... % chitobiose
            'EX_succ(e)', ... % succinate
            'EX_sucr(e)', ... % sucrose
            'EX_tre(e)', ... % trehalose
            'EX_Tn_antigen(e)',... % mucin o-glycan
            'EX_dsT_antigen(e)',... % mucin o-glycan
            'EX_C02528(e)', ... % chenodeoxycholate
            'EX_cholate(e)', ... % cholate
            'EX_dgchol(e)',... % chenodeoxyglycocholate
            'EX_gchola(e)',... % glycocholate
            'EX_tchola(e)',... % taurocholic acid
            'EX_tdchola(e)', ... % taurochenodeoxycholate
            'EX_xan(e)', ... %Xanthine
            'EX_hxan(e)',... %Hypoxanthine
            'EX_arbt(e)',... %Arbutin
            'EX_salcn(e)', ... %Salicin
            'EX_taur(e)', ... %Taurine
            'EX_gsh(e)'}; %Glutathione
% Make the lower bounds zero so nothing comes in through them
model=changeRxnBounds(model,reactionC,0,'l');
% Add aminoacids normalized by lactose
model=changeRxnBounds(model,{'EX_ala_L(e)', ... %Alanine
            'EX_arg_L(e)', ...  %Arginine
            'EX_asn_L(e)', ...  %Asparagine
            'EX_asp_L(e)', ...  %Aspartate
            'EX_cys_L(e)', ...  %Cysteine
            'EX_gln_L(e)', ...  %Glutamine
            'EX_glu_L(e)', ...  %Glutamate
            'EX_gly(e)', ...    %Glycine
            'EX_his_L(e)', ...  %Histidine
            'EX_ile_L(e)', ...  %Isoleucine
            'EX_leu_L(e)', ...  %Leucine
            'EX_lys_L(e)', ...  %Lysine
            'EX_met_L(e)', ...  %Methionine
            'EX_phe_L(e)', ...  %Phenilalanine
            'EX_pro_L(e)', ...  %Proline
            'EX_ser_L(e)', ...  %Serine
            'EX_thr_L(e)', ...  %Threonine
            'EX_trp_L(e)', ...  %Tryptophan
            'EX_tyr_L(e)', ...  %Tyrosine
            'EX_val_L(e)',...   %Valine
            'EX_alaasp(e)', ... %Alanyl Aspartate
            'EX_alagln(e)', ... %Alanyl Glutamine
            'EX_alaglu(e)', ... %Alanyl Glutamate
            'EX_alagly(e)', ... %Alanyl Glycine
            'EX_alahis(e)', ... %Alanyl Histidine
            'EX_alaleu(e)', ... %Alanyl Leucine
            'EX_alathr(e)', ... %Alanyl Threonine
            'EX_cgly(e)', ...   %Cysteinyl Glycine         
            'EX_glyasn(e)', ... %Glycyl Asparagine
            'EX_glyasp(e)', ... %Glycyl Aspartate
            'EX_glycys(e)', ... %Glycyl Cysteine
            'EX_glygln(e)', ... %Glycyl Glutamine
            'EX_glyglu(e)', ... %Glycyl Glutamate
            'EX_glyleu(e)', ... %Glycyl Leucine
            'EX_glymet(e)', ... %Glycyl Methionine
            'EX_glyphe(e)', ... %Glycyl Phenilalanine
            'EX_glypro(e)', ... %Glycyl Proline
            'EX_glytyr(e)', ... %Glycyl Tyrosine
            'EX_metala(e)', ... %Methionyl Alanine
            'EX_Ser_Thr(e)', ... %Protein-linked serine or threonine residue 
            'EX_metsox_R_L(e)', ... %Methionine sulfoxide 
            'EX_metsox_S_L(e)',... %Methionine oxide
            'EX_met_D(e)'}, ... % D-methionine
            -10^-1,'l');
% Add vitamines normalized by lactose
model=changeRxnBounds(model,{'EX_4abz(e)', ... %4-Aminobenzoate
            'EX_btn(e)', ... %Biotin
            'EX_fol(e)',... %Folate
            'EX_thf(e)', ... %5,6,7,8-Tetrahydrofolate
            'EX_5mthf(e)',... %5-Methyltetrahydrofolate
            'EX_nac(e)',... %Nicotinate
            'EX_pnto_R(e)',... %(R)-Pantothenate
            'EX_pydx(e)',... %Pyridoxal
            'EX_pydam(e)', ... %Pyridoxamine
            'EX_pydxn(e)', ... %Pyridoxine
            'EX_ribflv(e)'},... %Riboflavin
            -10^-3,'l');
% Add nucleotides normalized by lactose
model=changeRxnBounds(model,{'EX_ade(e)',... %Adenine
            'EX_thm(e)',... %Thiamin
            'EX_ura(e)'}, ... %Uracil
            -10^-2,'l');

% Add NGAM reaction
model=addReaction(model, 'ngam', 'metaboliteList', {'atp[c]','h2o[c]','h[c]','adp[c]','pi[c]'},'stoichCoeffList', [-1, -1, 1, 1, 1],...
'lowerBound', 0, 'upperBound' , 1000,'reactionName','ATP maintenance requirement','subSystem','Cellular maintenance');
% Add urea normalized by lactose (but eventualy it could be changed to
% accept free entry of urea using UREAabcpp with atp usage as gatekeep)
model=changeRxnBounds(model,{'EX_urea(e)'},-10^-1,'l');
% Because the reaction is anaerobic, make the oxygen lower bound zero
model=changeRxnBounds(model,'EX_o2(e)', 0 ,'l');
% To make sure of the production of all products, fix some upper bounds
model=changeRxnBounds(model,{'EX_val_L(e)','EX_leu_L(e)','EX_cys_L(e)','EX_ala_L(e)','EX_phe_L(e)','EX_pro_L(e)','EX_his_L(e)','EX_gln_L(e)','EX_glu_L(e)','EX_gly(e)','EX_ile_L(e)','EX_thr_L(e)'},0,'u');

% Add biomass reactions
for jx = 1:2
    switch jx
        case 1      % AGORA v1.03
            [stoic_bio,mets_bio] = xlsread('./data/Biomass Eqs B.infantis.xlsx','AGORA v1.03');
            rxnID_biomass = 'Biomass_growth_AGORA';            
        case 2      % Schopping et al.
            [stoic_bio,mets_bio] = xlsread('./data/Biomass Eqs B.infantis.xlsx','Schopping (adapted)');
%             [stoic_bio,mets_bio]=xlsread('./data/Biomass Eqs B.infantis.xlsx','Schopping (adapted) AGORA GAM');
            rxnID_biomass='Biomass_growth_Schopping';            
    end
    mets_bio(1,:)=[];
    mets_bio=mets_bio(:,1);
    model=addReaction(model, rxnID_biomass, 'metaboliteList', mets_bio,'stoichCoeffList', stoic_bio,...
        'lowerBound', 0, 'upperBound' , 1000,'reactionName',rxnID_biomass,'subSystem','Biomass formation');
end
model=changeObjective(model,'Biomass_growth_AGORA');

% Add additional information to the rxns and mets fields (extracted from BiGG DB)
[~,tdata] = xlsread('./data/mets_BiGG.xlsx','Metabolites');
tdata = tdata(2:end,:);
model.metKEGGID=tdata(:,6);
model.metChEBIID=tdata(:,7);
model.metHMDBID=tdata(:,8);
[~,tdata] = xlsread('./data/rxns_BiGG.xlsx','Reactions');
tdata = tdata(2:end,:);
model.rxnKEGGID=tdata(:,6);
model.rxnECNumbers=tdata(:,7);

%% Save final GENRE
model.modelID = 'iLR578';
clearvars -except model
save iLR578.mat